# Generated by Django 5.2.7 on 2025-11-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_others_posts', 'Moderator forum')]},
        ),
    ]
